# fly.toml app configuration file generated for leather-store on 2025-07-03T18:38:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'leather-store'
primary_region = 'yyz'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.http]
    port = 8080
    type = "http"
    interval = "15s"
    timeout = "2s"
    path = "/healthz"
    grace_period = "10s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
